groups:
- name: http_requests
  rules:
  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
    for: 5m
    labels:
      severity: critical
      team: api
    annotations:
      summary: "High error rate on {{ $labels.instance }}"
      description: "Error rate is {{ $value }}% for the last 5 minutes"

  - alert: HighLatency
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 2
    for: 10m
    labels:
      severity: warning
      team: api
    annotations:
      summary: "High latency on {{ $labels.instance }}"
      description: "95th percentile latency is {{ $value }}s"

- name: database
  rules:
  - alert: HighDatabaseConnections
    expr: pg_stat_activity_count > 50
    for: 5m
    labels:
      severity: warning
      team: database
    annotations:
      summary: "High number of database connections on {{ $labels.instance }}"
      description: "{{ $value }} active connections"

  - alert: DatabaseDown
    expr: pg_up == 0
    for: 1m
    labels:
      severity: critical
      team: database
    annotations:
      summary: "Database is down on {{ $labels.instance }}"

- name: system
  rules:
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
    for: 10m
    labels:
      severity: warning
      team: infrastructure
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"
      description: "Memory usage is {{ $value }}%"

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100 > 80
    for: 10m
    labels:
      severity: warning
      team: infrastructure
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "CPU usage is {{ $value }}%"

  - alert: LowDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"} < 10
    for: 15m
    labels:
      severity: warning
      team: infrastructure
    annotations:
      summary: "Low disk space on {{ $labels.instance }}"
      description: "Only {{ $value }}% space left on {{ $labels.mountpoint }}"

- name: application
  rules:
  - alert: HighErrorRate
    expr: rate(app_errors_total[5m]) > 10
    for: 5m
    labels:
      severity: warning
      team: backend
    annotations:
      summary: "High error rate in application"
      description: "{{ $value }} errors in the last 5 minutes"

  - alert: ServiceDown
    expr: up{job="app"} == 0
    for: 1m
    labels:
      severity: critical
      team: backend
    annotations:
      summary: "Service {{ $labels.instance }} is down"

  - alert: HighRequestLatency
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, endpoint)) > 5
    for: 10m
    labels:
      severity: warning
      team: backend
    annotations:
      summary: "High latency on {{ $labels.endpoint }}"
      description: "95th percentile latency is {{ $value }}s"

- name: business
  rules:
  - alert: NoNewUsers
    expr: increase(users_registered_total[1h]) == 0
    for: 1h
    labels:
      severity: warning
      team: product
    annotations:
      summary: "No new users in the last hour"

  - alert: HighFailureRate
    expr: rate(login_failures_total[5m]) / rate(login_attempts_total[5m]) > 0.2
    for: 15m
    labels:
      severity: warning
      team: security
    annotations:
      summary: "High login failure rate"
      description: "{{ $value }}% of login attempts are failing"

- name: custom
  rules:
  - alert: CustomMetricAlert
    expr: your_custom_metric > threshold
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Custom metric alert"
      description: "Custom metric value is {{ $value }}"
