"""Add loyalty models and relationships

Revision ID: 17d2d679224a
Revises: 1b05ba98f97f
Create Date: 2025-09-03 03:28:10.073473+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d2d679224a'
down_revision = '1b05ba98f97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', name='loyaltytier'), nullable=False),
    sa.Column('total_points_earned', sa.Integer(), nullable=False),
    sa.Column('total_points_spent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_accounts_id'), 'loyalty_accounts', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loyalty_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('EARN', 'SPEND', 'ADJUSTMENT', 'EXPIRATION', name='transactiontype'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loyalty_account_id'], ['loyalty_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_loyalty_accounts_id'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    # ### end Alembic commands ###
