"""Initial database schema

Revision ID: 2919dd9f24fa
Revises: 17d2d679224a
Create Date: 2025-09-04 00:59:20.748510+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2919dd9f24fa'
down_revision = '17d2d679224a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
