"""Add 2FA fields to User model

Revision ID: 38c49bc502ff
Revises: 2919dd9f24fa
Create Date: 2025-09-04 04:38:42.443143+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c49bc502ff'
down_revision = '2919dd9f24fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('backup_codes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'backup_codes')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'is_2fa_enabled')
    # ### end Alembic commands ###
