name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          python -m pytest tests/ --cov=app --cov-report=xml
        env:
          DATABASE_URL: postgresql://user:pass@localhost:5432/testdb
          SECRET_KEY: test-secret-key
          ENVIRONMENT: test

  deploy:
    name: Deploy to Production
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webkarmaapp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Railway
        uses: railwayapp/action@v1.0.0
        with:
          service: web
          environment: production
          token: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run migrations
        run: |
          # Add migration commands here
          echo "Running database migrations..."
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Verify deployment
        run: |
          # Add health check
          echo "Verifying deployment..."
          curl -sSf https://${{ secrets.RAILWAY_PROJECT_DOMAIN }}.railway.app/health
